# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questinfo',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='queststep',
            name='keywords',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
