# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0002_auto_20171121_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queststep',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='queststep',
            name='step_type',
            field=models.CharField(max_length=8),
        ),
    ]
